# Generated by Django 3.2.25 on 2026-01-12 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ipshieldapp', '0028_paymentlog_bill_exported_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessregistrationservice',
            options={'verbose_name': 'ĐKKD', 'verbose_name_plural': 'ĐKKD'},
        ),
        migrations.AlterModelOptions(
            name='copyrightservice',
            options={'verbose_name': 'Bản quyền', 'verbose_name_plural': 'Bản quyền'},
        ),
        migrations.AlterModelOptions(
            name='investmentservice',
            options={'verbose_name': 'Đầu tư', 'verbose_name_plural': 'Đầu tư'},
        ),
        migrations.AlterModelOptions(
            name='otherservice',
            options={'verbose_name': 'Dịch vụ khác', 'verbose_name_plural': 'Dịch vụ khác'},
        ),
        migrations.AlterModelOptions(
            name='trademarkservice',
            options={'verbose_name': 'Nhãn hiệu', 'verbose_name_plural': 'Nhãn hiệu'},
        ),
        migrations.RemoveField(
            model_name='businessregistrationservice',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='copyrightservice',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='investmentservice',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='otherservice',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='trademarkservice',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='businessregistrationservice',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/registration_certificates/', verbose_name='File chứng nhận đăng ký kinh doanh'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại hình kinh doanh'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='charter_capital',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vốn điều lệ'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên công ty'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đại diện pháp luật'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại chỉ được nhập chữ số', regex='^\\d+$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức danh'),
        ),
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='copyrightservice',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='copyrightservice',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Số chứng nhận'),
        ),
        migrations.AlterField(
            model_name='copyrightservice',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chủ sở hữu'),
        ),
        migrations.AlterField(
            model_name='copyrightservice',
            name='owner_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ chủ sở hữu'),
        ),
        migrations.AlterField(
            model_name='copyrightservice',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Loại hình tác phẩm'),
        ),
        migrations.AlterField(
            model_name='copyrightservice',
            name='work_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tác phẩm'),
        ),
        migrations.AlterField(
            model_name='investmentservice',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='investmentservice',
            name='investor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà đầu tư'),
        ),
        migrations.AlterField(
            model_name='investmentservice',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='Mục tiêu dự án'),
        ),
        migrations.AlterField(
            model_name='investmentservice',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã dự án'),
        ),
        migrations.AlterField(
            model_name='investmentservice',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên dự án'),
        ),
        migrations.AlterField(
            model_name='investmentservice',
            name='total_capital',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tổng vốn'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả dịch vụ'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người đại diện'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại chỉ được nhập chữ số', regex='^\\d+$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức danh'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='app_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Số đơn'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người nộp đơn'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='classification',
            field=models.TextField(blank=True, null=True, verbose_name='Nhóm sản phẩm/dịch vụ'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cấp'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='filing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày nộp đơn'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại chỉ được nhập chữ số', regex='^\\d+$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày công bố'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='trademark_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/trademark/', verbose_name='Hình ảnh nhãn hiệu'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='trademark_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nhãn hiệu'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID đối tượng')),
                ('certificate_file', models.FileField(upload_to='images/certificates/', verbose_name='File chứng nhận')),
                ('file', models.FileField(upload_to='images/certificates/', verbose_name='File đính kèm')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Tên file')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Loại đối tượng')),
            ],
            options={
                'verbose_name': 'Tài liệu đính kèm',
                'verbose_name_plural': 'Tài liệu đính kèm',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['content_type', 'object_id'], name='ipshieldapp_content_3eee72_idx'),
        ),
    ]
