# Generated by Django 3.2.25 on 2026-01-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0029_auto_20260112_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinstallment',
            options={'ordering': ['due_date', 'created_at'], 'verbose_name': 'Đợt thanh toán', 'verbose_name_plural': 'Các đợt thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='paymentlog',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Lịch sử thanh toán', 'verbose_name_plural': 'Lịch sử thanh toán'},
        ),
        migrations.AddField(
            model_name='contract',
            name='installment_interval_days',
            field=models.PositiveIntegerField(default=30, help_text='Số ngày giữa mỗi lần trả góp', verbose_name='Khoảng cách giữa các đợt (ngày)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_of_installments',
            field=models.PositiveIntegerField(default=1, help_text='Số lần trả góp (áp dụng khi chọn trả nhiều đợt)', verbose_name='Số đợt trả góp'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='bill_exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xuất hóa đơn'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='is_exported_bill',
            field=models.BooleanField(default=False, verbose_name='Đã xuất hóa đơn'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='trademarkservice',
            name='valid_date',
            field=models.DateField(blank=True, help_text='Ngày đơn được xác nhận hợp lệ', null=True, verbose_name='Ngày hợp lệ hóa đơn'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đến hạn'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='bill_exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xuất hóa đơn'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='ipshieldapp.contract', verbose_name='Hợp đồng'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ipshieldapp.paymentinstallment', verbose_name='Đợt thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='is_exported_bill',
            field=models.BooleanField(default=False, verbose_name='Đã xuất hóa đơn'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['contract', '-paid_at'], name='ipshieldapp_contrac_7363e6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['installment', '-paid_at'], name='ipshieldapp_install_b85045_idx'),
        ),
    ]
