# Generated by Django 5.2 on 2026-03-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0031_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Lần đăng nhập cuối"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Mật khẩu"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profile",
                to="ipshieldapp.customer",
                verbose_name="Khách hàng liên kết",
            ),
        ),
    ]
