# Generated by Django 5.2 on 2026-04-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0032_customer_last_login_customer_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Đăng Nhập"),
                            ("logout", "Đăng Xuất"),
                            ("view_contract", "Xem Hợp Đồng"),
                            ("change_password", "Đổi Mật Khẩu"),
                            ("update_profile", "Cập Nhật Hồ Sơ"),
                        ],
                        max_length=30,
                        verbose_name="Hành động",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="ipshieldapp.customer",
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký hoạt động KH",
                "verbose_name_plural": "Nhật ký hoạt động KH",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ipshieldapp_created_e51b75_idx"
                    )
                ],
            },
        ),
    ]
