# Generated by Django 6.0 on 2026-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0033_customeractivitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeractivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Đăng Nhập"),
                    ("logout", "Đăng Xuất"),
                    ("view_contract", "Xem Hợp Đồng"),
                    ("change_password", "Đổi Mật Khẩu"),
                    ("update_profile", "Cập Nhật Hồ Sơ"),
                    ("support_request", "Yêu Cầu Hỗ Trợ"),
                ],
                max_length=30,
                verbose_name="Hành động",
            ),
        ),
    ]
