# Generated by Django 6.0 on 2026-04-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0034_alter_customeractivitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/avatars/",
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
