# Generated by Django 5.2 on 2026-04-09 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0035_customer_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/contracts/", verbose_name="Ảnh chụp hợp đồng"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tên ảnh"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày tải lên"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_images",
                        to="ipshieldapp.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ảnh hợp đồng",
                "verbose_name_plural": "Ảnh hợp đồng",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
