# Generated by Django 6.0 on 2026-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0036_contractimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="bussiness_license",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="images/business_licenses/",
                verbose_name="File giấy phép kinh doanh",
            ),
        ),
    ]
