# Generated by Django 6.0 on 2026-04-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0037_customer_bussiness_license"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="bussiness_license",
            new_name="business_license",
        ),
    ]
