# Generated by Django 6.0 on 2026-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0038_rename_bussiness_license_customer_business_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="register_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Năm đăng ký"
            ),
        ),
    ]
