# Generated by Django 6.0 on 2026-04-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0039_customer_register_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="register_year",
            field=models.DateField(blank=True, null=True, verbose_name="Năm đăng ký"),
        ),
    ]
