# Generated by Django 6.0 on 2026-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0040_alter_customer_register_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="deny_document",
            field=models.FileField(
                blank=True, null=True, upload_to="images/deny_documents/"
            ),
        ),
    ]
