# Generated by Django 6.0 on 2026-04-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0041_contract_deny_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="deny_document",
        ),
    ]
