# Generated by Django 6.0 on 2026-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0042_remove_contract_deny_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="trademarkservice",
            name="deny_document",
            field=models.FileField(
                blank=True, null=True, upload_to="images/deny_documents/"
            ),
        ),
    ]
