# Generated by Django 6.0 on 2026-04-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0043_trademarkservice_deny_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trademarkservice",
            name="deny_document",
            field=models.BooleanField(default=False, verbose_name="Tài liệu từ chối"),
        ),
    ]
