# Generated by Django 5.2 on 2026-04-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0044_alter_trademarkservice_deny_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trademarkservice",
            name="deny_document",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày từ chối"),
        ),
    ]
