# Generated by Django 5.2 on 2026-04-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0045_alter_trademarkservice_deny_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="trademarkservice",
            name="is_denied",
            field=models.BooleanField(default=False, verbose_name="Bị từ chối"),
        ),
    ]
