# Generated by Django 5.2 on 2026-04-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0046_trademarkservice_is_denied"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trademarkservice",
            name="is_denied",
        ),
    ]
