# Generated by Django 5.2 on 2026-04-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0047_remove_trademarkservice_is_denied"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="images/customer_documents/",
                        verbose_name="File đính kèm",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tên file"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày tải lên"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ipshieldapp.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài liệu khách hàng",
                "verbose_name_plural": "Tài liệu khách hàng",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
