# Generated by Django 5.2 on 2026-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0048_customerdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("left", "Bên trái"), ("right", "Bên phải")],
                        max_length=10,
                        unique=True,
                        verbose_name="Vị trí",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="Ảnh banner"),
                ),
                (
                    "link",
                    models.CharField(
                        choices=[
                            ("https://ipsystem.vn/", "IPSystem"),
                            ("https://ipleader.vn/", "IPLeader"),
                        ],
                        max_length=100,
                        verbose_name="Link",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hiển thị"),
                ),
            ],
            options={
                "verbose_name": "Banner Portal",
                "verbose_name_plural": "Banner Portal",
            },
        ),
    ]
