# Generated by Django 6.0 on 2026-05-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0049_portalbanner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="status",
        ),
    ]
