# Generated by Django 6.0 on 2026-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0051_servicetype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="service_type",
        ),
        migrations.AddField(
            model_name="contract",
            name="services",
            field=models.ManyToManyField(
                related_name="contracts", to="ipshieldapp.servicetype"
            ),
        ),
    ]
