# Generated by Django 6.0 on 2026-05-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0053_alter_businessregistrationservice_contract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessregistrationservice",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business",
                to="ipshieldapp.contract",
            ),
        ),
        migrations.AlterField(
            model_name="investmentservice",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investment",
                to="ipshieldapp.contract",
            ),
        ),
        migrations.AlterField(
            model_name="otherservice",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_service",
                to="ipshieldapp.contract",
            ),
        ),
    ]
