# Generated by Django 6.0.3 on 2026-07-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0054_alter_businessregistrationservice_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='ipshieldapp.contract'),
        ),
        migrations.AlterField(
            model_name='investmentservice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='ipshieldapp.contract'),
        ),
    ]
