# Generated by Django 6.0.5 on 2026-07-03 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0055_alter_businessregistrationservice_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Mã số thuế chỉ được nhập số và dấu gạch ngang (-)', regex='^[0-9-]+$')], verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_services', to='ipshieldapp.contract'),
        ),
    ]
