# Generated by Django 6.0.5 on 2026-07-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0056_alter_customer_tax_code_alter_otherservice_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('VND', 'VNĐ'), ('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('KRW', 'KRW')], default='VND', max_length=3, verbose_name='Loại tiền tệ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Giá trị hợp đồng'),
        ),
    ]
